apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: minio-accessor
    image: timv2/minio-fuse:0.0.3
    securityContext:
      privileged: true
    envFrom:
    - secretRef:
        name: minio-fuse
  restartPolicy: Never