apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - name: minio-accessor
    image: timv2/minio-fuse
    securityContext:
      privileged: true
    envFrom:
    - secretRef:
        name: minio-fuse
